### ISSUE TITLE
macOS build an universal binary for ARM/aarch64 and Intel/x64

### ISSUE THREAD

**Issue by DaveFlashNL** [mixxxdj/mixxx#10867]
Application is now intel,

please consider building for modern architecture on macOS, 
to take advantage of all that Apple Silicon has to offer.

Then after building for Apple Silicon, combine the binaries to 
create a Universal 2 Application for all mac's

many thanks

**Comment by daschuer** [comment]
I think we should not do this. It will likely increase the complexity of the build process and will double up the size of the delivered binary. The only benefit it that the user does not need to know which binary he has to download and not accidental run a Intel binary on an M1 hardware running using Rosatta which is known as a magnitude slower than a native build. 

Maybe we can instead warn the user and redirect him to the native build, once we have and M1 build ready.

By the way I have an experimental M1 build here: 
https://github.com/daschuer/mixxx/actions/runs/2638298438

**Comment by DaveFlashNL** [comment]
we absolutley do, as the avarage user is not gonna know what cpu's he got, also, apple will deprecate intel in a short while. it's advised to build for apple silicon sooner rather then later in my opinion...

**Comment by daschuer** [comment]
Do you have interest to help?

**Comment by fwcd** [comment]
I agree, official ARM macOS binaries would be nice and there is work underway to make it happen, but I would also vote against universal binaries, primarily due to space concerns. Figuring out whether someone has an M... processor isn't too hard. I think there are even Web APIs to read the CPU architecture (see [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/PlatformArch)), so we could simply serve the user the correct download link for their OS/arch combo.
