### ISSUE TITLE
Win 10: High CPU load Radeon RX 480 and GL waveform

### ISSUE THREAD

**Issue by RodSmart** [mixxxdj/mixxx#10933]
### Bug Description

No Tracks Loaded Into Decks = 1 or 2% CPU
1 Track Loaded but not playing = about 10% CPU
2 Tracks Loaded but not playing = about 35% CPU
2 Tracks Loaded and 1 playing = 100% CPU and jerky animations on interface. Same result with waveforms switched off.
Task Manager only shows 10% CPU and less than 50% memory usage.
Nothing else running at the time
Mixxx Ver 2.3.3 running on fairly new HP laptop AMD Ryzen 3 3300U with Radeon Vega graphics.
Windows 10
 

### Version

2.3.3

### OS

Windows 10 64 Bit

**Comment by veeroohre** [comment]
I have a similar problem. No track loaded but very high cpu load. 
Since the load drops to approx. 50 when pressing "space" my suspicion is it's gpu related (even though no track is loaded and therefore no waveform is shown).
I have a AMD radeon RX480 with the latest stable drivers (see screenshot) and an Intel Core i5-6600K. Quite old but playing games like Doom Eternal or Division 2 run ok. Think these games should stress the GPU more. 

"--saveMode" did not change anything. Changing skin to "Deere" did not help, too.

![mixxx](https://github.com/mixxxdj/mixxx/assets/8831160/6101bd82-a675-4bfb-a4fb-77ce3c5ac807)
![radeon](https://github.com/mixxxdj/mixxx/assets/8831160/dbf8a50f-12b6-41e4-915e-2336b8598c63)

**Comment by ronso0** [comment]
Before we try to debug this, please try 2.4-beta

**Comment by veeroohre** [comment]
I tried it. Unfortunately same result. I also tried it under Ubuntu. There the CPU load was significantly lower.

**Comment by daschuer** [comment]
I don't think that the NAS alone is the culprit in your case. 
Since "--saveMode" does not change the issue, we can also rule out waveform/GPU issues. 
Interestingly all CPUs are equal used. The most CPU consuming Audio thread is a single CPU issue. Ideally Windows should schedule it in the same CPU core to keep the core cache hot. @JoergAtGithub: Is this the case in windows? 
Mixxx uses multi theads for analysis and caching tracks. 
This is done after Mixxx has been idle for a while. 
Can you confirm this or is the CPU load always high? 

I can also imagine that a virus scanner is extra thoroughly and does some work from the Mixxx process. Does the problem remain if you pause all security applications?

**Comment by daschuer** [comment]
Which Audio API do you use with which buffer size?

**Comment by veeroohre** [comment]
Is save mode implemented in the beta?
![Unbenannt](https://github.com/mixxxdj/mixxx/assets/8831160/b17a1db8-c430-4949-8e72-beaf59d880db)

**Comment by daschuer** [comment]
Oh sorry for the typo, it is --safeMode.

**Comment by daschuer** [comment]
Unrelated: The GUI alignment in the audio preferences can be improved.

**Comment by veeroohre** [comment]
I tried it again and it works. Now the load is around 1 to 2%

So it's a graphical/GPU issue?

I change the frame rate to 60. Could that be a problem?

**Comment by veeroohre** [comment]
> Unrelated: The GUI alignment in the audio preferences can be improved.

Do you mean by me? I shrinked it to save some screenshot space.

**Comment by veeroohre** [comment]
![Unbenannt](https://github.com/mixxxdj/mixxx/assets/8831160/3dcf46c1-fc2c-42a3-91e9-5429b3b34d67)

**Comment by daschuer** [comment]
No. Every recent device should be able to do 60 Hz.
Can you try to run without the flag again and check if any of the waveform option fix the issue? 

Does disabling spinnies change something or the flag: 
--disable-vumetergl

**Comment by veeroohre** [comment]
"--disable-vumetergl" seems to lower the cpu load further but not as much as "safemode" does.

![Unbenannt](https://github.com/mixxxdj/mixxx/assets/8831160/5066b8ce-d90e-4a34-ada9-1d0e77d729dd)

**Comment by veeroohre** [comment]
When I use "Simple (GL)" cpu goes up to maximum possible (around 80%). But even "empty" takes 45-50% cpu

**Comment by veeroohre** [comment]
@daschuer Do you need more information or did I miss something?

**Comment by daschuer** [comment]
> Edit: All GL(SL) settings cause maximum cpu load. Maybe an OpenGL issue?

Ok, so you have a working setup with non GL waveforms, right? 

Since we have reports from other windows 10 users that Mixxx 2.3.5 works good and 2.4-alpha works even better with GL waveforms, it can be a configuration issue on your side. 

Did you use any non default settings in a Radeon tweak tool? There is also the Adrenaline 23.5.2 driver available and the Pro 22.Q4 with a slightly advanced driver version number. It is however suspicious that it is offered for download but the RX 480 is not listed in the release notes.

**Comment by veeroohre** [comment]
Yes, it's working but with a high cpu load. I will try to use a different driver and see if it helps. This is really strange because I can run 3d games without a problem.

I only use the drivers and no additional tools (and therefore tweaks) from AMD. Too much bloatware in my opinion.

Since I am the only one with this problem you could close this issue.

**Comment by veeroohre** [comment]
Sorry, not now. I'm on vacation soon. Will come back to you after my return.

Am Di., 27. Juni 2023 um 13:23 Uhr schrieb JoergAtGithub <
***@***.***>:

**Comment by JoergAtGithub** [comment]
The latest Beta contain further waveform fixes for Windows. It would be great if you could retest it again.

**Comment by daschuer** [comment]
Thank you for your confirmation. I think we can close it than. Please reopen if you still see an issue.
