### ISSUE TITLE
Tag Fetcher: allow applying tags and new cover art separately

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11086]
### Feature Description

#4851 
With the current state of #4851 cover art is looked up based on each tag result, though best-matching tags may not coincide with best-matching/preferred cover art.

Let's split the dialog so that we have separate "Apply tgas" and "Apply cover art" controls.

**Comment by daschuer** [comment]
Cover and Matadata are to together one entity. 

You may have a recording of a single/EP, with the EP cover and the according Album name. 
Than you have often the Album/LP recording with the related cover Art and various sampler or greatest hits recordings. 

Using the Album name but the single cover feels wrong and should be the exceptional case. In the same way you may use the original release date, but keep the rest as "Best of" Album instead of the release date of the "Best of"

So I think we should not implement this. If we have a use case for it we may consider a solution to make all individual selectable. Do we?

**Comment by ronso0** [comment]
Yes, I showed a use case [here](https://github.com/mixxxdj/mixxx/pull/4851#issuecomment-1321245931)
It's unrelated to album vs. EP or Best Of

"Mark Pritchard - Under The Sun" ([MB response](https://musicbrainz.org/ws/2/recording/9ec9b97b-e3bb-4d75-85fe-0fa0705881e5?inc=artists+artist-credits+releases+release-groups+media))
* the first two hits have the correct tags I would pick, but only the first one has a cover and that is only 400 x 400 px
* the last result has some pre-release tags but large cover art (1000 x 1000 px)

both have the same correct image but different resolution.
![image](https://user-images.githubusercontent.com/5934199/203080283-98c3576a-ff34-46ce-a6df-d4f50d0599bb.png)

**Comment by Holzhaus** [comment]
> 1963 quickly becomes 2011 when some remaster was released

Notr that the date tag is for release dates, and there is a separate tag for the original release date.

Not sure if mixxx supports it yet tough.

> Unfortunately this feature now (as it is in Mixxx 2.4 beta 70) is not usable, since the other Tags from MB are in most cases not accurate (only Big Letters, only small letters , mix of both etc...

In my experience the MB Tags are quite accurate and usually match the writing on the cover art. For cases that the tag is wrong there should be a button to open the track on the MB website, so you can fix the tags directly for everyone by changing it in the Musicbrainz database.

Just my 2 cents, as I personally use beets for tagging instead of Mixxx.

**Comment by Cantuccini-Lori** [comment]
Believe me, for older Music they are not Accurate :)
And mixxx supports only Date. Sure Release date would be more precise, but even on MB its poorly supported.

**Comment by daschuer** [comment]
My guess is that you can find examples for both. 
So this request here is valid. 

What does it mean to contribute metadata changes back? 
@Holzhaus can you file a separat isdue for it? 

What is the killer feature of beets missing in Mixxx? 
Maybe we can track that as issue as well. The Duscogs integration looks appealing.

**Comment by ronso0** [comment]
This feature request, as demonstrated in the 1st post, is about applying cover art independent from tags because the best-matching MusicBrainz tag set (release id) and best cover from coverartarchive are both individual decisions.

Let's track other metadata features separately.

**Comment by ronso0** [comment]
Fixed by #11938
