### ISSUE TITLE
CI: Installing qml_formatter fails with "Executable `rustup` not found"

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11386]
### Bug Description

All recent CI builds of various PRs for 2.4/Main fail:
![grafik](https://user-images.githubusercontent.com/64457745/226109088-716d721a-5167-48a4-a133-af8a6cf43416.png)

for example: https://github.com/mixxxdj/mixxx/actions/runs/4455587774/jobs/7825486519?pr=10989

### Version

2.4.0/Main

### OS

Pre-Commit

**Comment by daschuer** [comment]
It might be caused by an pre-commit update.
This ins one of the last working runs: 
https://github.com/mixxxdj/mixxx/actions/runs/4448394360/jobs/7811151308
Downloading pre_commit-3.1.1-py2.py3-none-any.whl (202 kB)

This is a failing one: 
https://github.com/mixxxdj/mixxx/actions/runs/4451827087/jobs/7824682752
Downloading pre_commit-3.2.0-py2.py3-none-any.whl (202 kB)

**Comment by daschuer** [comment]
There is no easy way to pin the pre-commit version: 
https://github.com/pre-commit/action/blob/main/action.yml

I think it is best to temporary disable the almost not used qml_formatter until upstream has a fix.

**Comment by daschuer** [comment]
This is the upstream bug: https://github.com/pre-commit/pre-commit/issues/2823
