### ISSUE TITLE
Tracks with umlaut only being treated correctly until restart

### ISSUE THREAD

**Issue by Andymann** [mixxxdj/mixxx#11406]
### Bug Description

Clean installation, empty database etc.  
Track is "Herbert Grönemeyer - Männer.mp3". ID3V2-Tag: Artist:Herbert Groenemeyer Title:Männer  
  
Folder containing this track is added to the library via settings-dialog. The track is listet in the library when no search-term is used. See attached screenshot_1. 
Searching for 'männer' fails: track is not shown in search-results. See screenshot_2. 
  
Loading the track into a deck, THEN searching for 'männer' succeeds/ fails.  
Many times searching for the track succeeds when it's already loaded into a deck.  
If searching for the track (already loaded) fails then it helps to set a hotcue. Then the track can be found in the library again - until application restart. I could not find out what triggers this. Rebooting the computer makes this scenario succeed again.

<img width="1440" alt="screenshot_1" src="https://user-images.githubusercontent.com/2955327/227740590-7bbc16b1-8bc0-4581-8f1e-b2f97081b839.png">
<img width="1440" alt="screenshot_2" src="https://user-images.githubusercontent.com/2955327/227740598-cf0520e2-8dda-4fb8-aa99-98d0d19b150b.png">
<img width="1440" alt="screenshot_3" src="https://user-images.githubusercontent.com/2955327/227741080-57d8ba8f-a0e5-42c8-aff9-7638318ac189.png">

### Version

2.3.4

### OS

macOS Monterey

**Comment by foss-** [comment]
This was a known issue on Linux however never reproduced: https://github.com/mixxxdj/mixxx/issues/10613
Two bugs for Mixxx on macOS mention similar issue, but in a test with a recent test version I am no longer able to reproduce:
https://github.com/mixxxdj/mixxx/issues/9892
https://github.com/mixxxdj/mixxx/issues/11103

@Andymann could you please test https://mixxx.org/download/#testing and report back if the issue is persisting for you? Sidenote: My tests were done on macOS 13.2.1.

**Comment by Andymann** [comment]
Quick test with mixxx 2.4-alpha-1423-gcffc528e1c (main):

Problem is not reproducible

(I could close it but wanna be sure it's okay)
