### ISSUE TITLE
Auto Dj Stops itself

### ISSUE THREAD

**Issue by DelGes** [mixxxdj/mixxx#11448]
### Bug Description

Hello, I experienced the same problem as described in this thread:

https://bugs.launchpad.net/mixxx/+bug/1961970

and here:

https://mixxx.discourse.group/t/auto-dj-starts-and-stops-itself/24268/69

I experienced the same problem on Mixxx 2.3.3 and currently on Mixxx 2.3.4 (on MacOS Catalina 10.15.7).

After some time Auto DJ randomly stops and I have to manually click „play”. I can’t find the pattern of this bug.
I read that in version 2.3.3. This bug should be fixed, but it turns out that there is still something wrong. The issue appears very rarely, so only once I've been able to reproduce it. But I experienced this issue on two different live sessions, on two different versions (Mixxx 2.3.3 and 2.3.4). Every time, during 4 hour DJ set, I had around two incidents with this bug 

I can attach logs and more info, if this is necessary. This is a serious issue, because currently – due to this bug – I don’t consider Mixxx as stable app for live performances anymore. 

### Version

2.3.4

### OS

MacOS Catalina 10.15.7

**Comment by daschuer** [comment]
Let's look at 2.3.4 only. The forum thread and bug you linked describe a different issue that is fixed. 

Please describe you Auto DJ fade mode and transition time. Did you make use of the intro/outro feature? 
Can you identify the previous and nest track when the Auto-DJ stops? 
A mixxx.log from the session where the auto DJ stops would be also helpful.

**Comment by DelGes** [comment]
Fade mode: „skip silence”
Transition time: -4 sec.
I didn’t use any more advanced options. I use Auto DJ for playing playlists during tango events. I use only „skip silence” feauture to have fixed time of silence between songs. 
During the last set Auto DJ stoped twice:
1) after „2. Si-la-llegaran-a-ver.mp3” file and before „3. Barranca-abajo.mp3”
2) after „1. Amarga-sospecha.mp3” file and before „2. Santa-madrecita.mp3”
I attached mixxx.log

[mixxx.log.1.zip](https://github.com/mixxxdj/mixxx/files/11177526/mixxx.log.1.zip)

**Comment by daschuer** [comment]
Do you have an idea what this warning is about? 
`Warning [Main]: QString::arg: Argument missing: Dostosuj, Wysokie`

**Comment by DelGes** [comment]
„Dostosuj” means „adjust” and „wysokie” means „high” and it could be related to gain for high filter. That’s all I understand from this. 

If that would be helpful I have more logs, but from version 2.3.3. Same issue.
– "mixxx.log.2" comes from my previous DJ set. I don’t know after which track it stopped. 
– "mixxx.log": after that issue I tried to reproduce the issue in my home, and I did it once. Auto DJ stopped after the „A La Luz Del Candil” track. 


[Logs.zip](https://github.com/mixxxdj/mixxx/files/11199158/Logs.zip)

**Comment by daschuer** [comment]
Fixed the translation issue. https://github.com/mixxxdj/mixxx/commit/3344da6224474dcafa267673e8daa58479b7e630

**Comment by daschuer** [comment]
I think I have found the issue:
Due to https://github.com/mixxxdj/mixxx/issues/11159 fixed by https://github.com/mixxxdj/mixxx/pull/11168
The track length can change, which causes the Auto DJ fail reaching the original analysand silence start position. 

I have prepared a test build fixing both issue: 
https://github.com/daschuer/mixxx/suites/12231378819/artifacts/646992672 (GitHub login required) 

@DelGes Please verify.

**Comment by daschuer** [comment]
Currently we have no menu entry to fix the Audible Sound Cue. Since we have no other marker for the Audible Sound than the waveforms, it would be naturally to reset the Audible Sound Cue whenever the waveform is reset. I consider this as a natural solution without bother the user to deal with invisible data and an extra Menu. 

What do you think? 

In such siltation every track annotation will be off. But at least it is visible after the waveform is reanalysed and the user can take the right decision to fix beatgrid and cues as well.

**Comment by DelGes** [comment]
> I think I have found the issue: Due to #11159 fixed by #11168 The track length can change, which causes the Auto DJ fail reaching the original analysand silence start position.
> 
> I have prepared a test build fixing both issue: https://github.com/daschuer/mixxx/suites/12231378819/artifacts/646992672 (GitHub login required)
> 
> @DelGes Please verify.

Thank you, so far everything works, but as I said, it is very hard for me to reproduce this issue. Sometimes after a couple of hours playing music nothing wrong happens. If I experience this issue again, I will report it. All the best.
