### ISSUE TITLE
adding mixer with VU meters slows down the whole program

### ISSUE THREAD

**Issue by solitprojects** [mixxxdj/mixxx#11556]
### Bug Description

Since upgrade to [2.3.5] , when I add the "mixer" on screen, the program reacts very slow. Even when it's not playing anything. Every click has a delay of at least several seconds, and it gets worse when you start playing

Are there others facing the same issue?

### Version

2.3.5

### OS

macOS Ventura 13.3.1a

**Comment by ronso0** [comment]
Could you please run Mixxx from the command line and add the `--disableVuMeterGL` argument?
https://manual.mixxx.org/2.3/en/chapters/appendix/commandline_dev_tools.html#launching-mixxx-from-the-command-line

Does it make any difference?

**Comment by solitprojects** [comment]
this seems to solve it indeed, it's way better

**Comment by JoergAtGithub** [comment]
Could you try the following development build of PR10989: https://github.com/mixxxdj/mixxx/suites/12873892391/artifacts/694473745

Does this build show the same slowness?

**Comment by solitprojects** [comment]
thanks for this quick answer!
dev version is working smooth as well

**Comment by JoergAtGithub** [comment]
Thanks for testing!

**Comment by ronso0** [comment]
@solitprojects So your options (while waiting for Mixxx 2.4-beta ;) are
* revert to the version you used previously (you may encounter severe bugs that have already been fixed in 2.3.5, also downgrading _may_ cause issues in your library)
* keep Mixxx 2.3.5 and create a custom launcher with the (yet undocumented) `--disableVuMeterGL` argument added (I'm not into macOS, looks like a shell script is the easiest way)
