### ISSUE TITLE
Distorted UI

### ISSUE THREAD

**Issue by okedialf** [mixxxdj/mixxx#11564]
### Bug Description

My mixxx UI is completely distorted. My Operating system is:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

![image](https://github.com/mixxxdj/mixxx/assets/10192723/38c6bc9e-871b-4bd3-a12c-12446c38896a)

Please assist.

### Version

2.3.5

### OS

Ubuntu 22.04.2 LTS

**Comment by ronso0** [comment]
Is this a clean install, i.e. no earlier version was installed?

Where did you get the installer from?
What's your desktop? Plain Ubuntu with Gnome?
Did you scale the UI?

**Comment by okedialf** [comment]
Yes, the scale factor was the issue. I'd earlier adjusted it to 0.95. Restoring it to 1 fixed the distortion.
Thanks for pointing me into the right direction.

**Comment by ronso0** [comment]
How did you set the scale factor?

**Comment by okedialf** [comment]
On terminal: 
`gsettings set org.gnome.desktop.interface text-scaling-factor 0.9`

To reset:
 `gsettings set org.gnome.desktop.interface text-scaling-factor`

**Comment by ronso0** [comment]
Okay, I see.
First thing to note is that in the Mixxx GUI most buttons and labels are fixed in size and fonts properties are chosen to match in order to always fit the claimed minimal required screen size. So the Mixxx skins are really responsive layouts as some other apps.
`gsettings set org.gnome.desktop.interface text-scaling-factor` just addresses the fonts, so it seems this is not the preferred way to scale the desktop (especially for downscaling, there are other ways, just found [this discussion](https://www.reddit.com/r/gnome/comments/vqcajd/set_ui_scale_to_less_than_100/)).

Nevertheless, it'd be interesting what results you get if you combine that gnome setting with the Mixxx-preferred way described in the wiki https://github.com/mixxxdj/mixxx/wiki/troubleshooting#graphical-user-interface-gui-is-too-big-or-too-small (i.e. set both the gnome and the Qt setting to 90%)
