### ISSUE TITLE
Re-add Crossfader re-center when disabling auto DJ

### ISSUE THREAD

**Issue by tlibra10** [mixxxdj/mixxx#11571]
### Feature Description

I would like to request for the crossfader auto re-set to be re-instated to the next update of Mixxx.

Thank You.

**Comment by daschuer** [comment]
This feature has been removed to fix bug: 
https://github.com/mixxxdj/mixxx/issues/10683
here:
https://github.com/mixxxdj/mixxx/pull/4714

Please explain why you want to have  that feature back. Maybe you have also an idea how it could be brought back without re-introducing the fixed bug.

**Comment by tlibra10** [comment]
I have been away from the decks a few times. Sometimes at home sometimes live. And on both occasions I have forgot to re-center the crossfader after disabling the auto dj. Started the next track and "Nothing" then realized that I did not re-center the crossfader. Therefore I decided to go back to version 2.3.2 as that one re-centers automatically.
I feel that this is a really useful feature. 
It also happened at a party and I felt so embarrassed. So for now I will stay with 2.3.2 as that is quite a good version anyway.  
Thank you.

**Comment by mxmilkiib** [comment]
Proposal; the fader to move over the course of one second from the AutoDJ position to the centre on disabling the AutoDJ, a slewed transition, so the audio won't pop. PRs welcome. Could that be the situation?

**Comment by ronso0** [comment]
IMHO no, volume will still drop even though there is no actual track-to-track transition, just slower than the instant reset.

I think the best idea that came up was the "Re-center crossfader when disabling AutoDJ" option in the preferences (default OFF). If users don't like the default I assume they'd look in the AutoDJ preferences first.

**Comment by mxmilkiib** [comment]
Ok.

Sorry, I actually misread what the problem was, on one of the other dupes.

Yeah, that option you suggest is the easiest fix.

I mean, I guess ultimately the problem should be stated as: "AutoDJ doesn't know how to deal with 'the end of the mix' phase of a mix"?

To make it consistent, the exact time the user turns off AutoDJ should not be the exact time AutoDJ does it's last action; it should play the current track it into end, then finish.

But I've seen it said that adding more automation is extraneous magic. But finishing a mix is an integral part of a mix. 

So the underlying tension here is that there's more than one reason a user wants to use AutoDJ: Some want it to create nice mixes, say for a hospital radio, etc. and others just want to be able to immediately stop it for reference reason.

But, indeed, the easiest solution is an option. (A harder one would be too let the user choose at the point of turning AutoDJ off, but probably the user will consistently want the same outcome, so there's no need for such magic.)

**Comment by ronso0** [comment]
> I mean, I guess ultimately the problem could be stated as: "AutoDJ doesn't know how to deal with 'the end of the mix' phase of a mix"?

Not quite IMHO. I wrote a lot about this topic already, for example #4714, I'll try to summarize my thoughts on it.

Reading the various bug reports I think there are two perspective:
**1)** Users got acustomed to to re-center and want it back because their workflow is broken (Hyrum's Law, https://xkcd.com/1172/)
**2)** Users (ab)use Mixxx as auto-player with manual intervention and expect **Auto**DJ to know what they want and act accordingly. My impression is this group doesn't know and/or doesn't care about DJ'ing basics (crossfader? anyone?).

The dilema with AutoDJ is: it interferes with the user-set mixing controls  (it has to), but can't reliably predict what the user is up to when AutoDJ **finishes**. (maybe some future AI can, after observing he DJ for while)
The original use case was:
the DJ is mixing and AutoDJ should give them a break. Then when they want to takeover again, i.e. check controls, maybe re-sync controllers, and continue mixing. **What exactly** they're doing we can't guess. Maybe check some tracks on the opposing deck? Maybe talk over the last track's outro? Load a track and hit Play right away? Mix with the Vol faders? Mix with the crossfader? :shrug: 

**IMO the bottom line is, UX-wise:**
AutoDJ must be **predictable**.
I.e. when it is **not** engaged (i.e. is not in control of the adjacent deck and the crossfader) it should **not** touch anything. 
It can start in any situation, regardless the crossfader position.
Auto-mixing means it moves the crossfader over to the **new** track, mixing at predefined points in time.
Why should it center the crossfader after the last track?

I mean users seem to have figured the Vol faders need to be up for auto-mixing to work, i don't understand why it is so diffult to take care of the crossfader themselves.

The re-center option is the least-invasive and pragmatic solution, even though I only partly agree this is a valid feature request in the first place.
