### ISSUE TITLE
Encrypt Icecast password  in C:\Users\xxx\AppData\Local\Mixxx\broadcast_profiles\Icecast.bcp.xml

### ISSUE THREAD

**Issue by ikr83** [mixxxdj/mixxx#11651]
### Feature Description

Hello, 

To broadcast 'on air' from Mixxx, I use Icecast. In the config files, there is C:\Users\david\AppData\Local\Mixxx\broadcast_profiles\Icecast.bcp.xml, and in the Icecast.bcp.xml file, on line 10, I have my connection parameters and my password in plain text. Is there a solution where the password is not readable in plain text? AES 128-bit encryption of the password, perhaps? Maybe it's possible to create a C++ script that encrypts the password before storing it in the XML, using an encryption key provided by the user. Then, another C++ script can decrypt the password before sending it to Icecast using the encryption key?

:)

**Comment by uklotzde** [comment]
This would require to ask the user for the password whenever this data needs to be decrypted. At least once after startup.

Using a hard-coded password or storing it in the configuration would be pointless.

**Comment by uklotzde** [comment]
But the actual question is "Why?". Private configuration files are not supposed to be shared or stored in private places. I don't consider this a desirable feature.

**Comment by uklotzde** [comment]
Mixxx already uses [QtKeychain](https://github.com/frankosterfeld/qtkeychain), but I have no clue how and where.

**Comment by ikr83** [comment]
To connect to a remote server, it is preferable to use a strong password. Storing this password in plain text poses a security issue for me. Using an encryption key to store an encrypted version of the password does require entering the key at the application startup (or at the start of the broadcast). I prefer entering an encryption key like "8956" rather than a password like "h8UkHxD$95SLWC". I understand that the encryption key is weak, but the exposure of my local data is less significant than a server connected to the internet. I agree that configuration files are not supposed to be shared in a single-user environment. However, if you work with multiple machines and want to synchronize your config files, they may need to travel...

**Comment by Swiftb0y** [comment]
Encrypting a password locally with a weak key does nothing more than bother the user since any weak key would be easy enough to bruteforce anyways and any strong key would be just as inconvenient as the actual password. 

As already pointed out, we do make use of QtKeychain for encrypting the broadcast credentials though I don't how exactly that plays out when sharing configs as those credentials are likely stored by the operating system and not in the config. 

If you do share your config with other people I suggest its best to create a config without credentials and only tell them on demand. Even better and likely the only actually secure option is if you have control over the icecast server. Then create different endpoints with different credentials that are only valid for the timme that each user is supposed to have access. 

Either way. I don't the solution you suggested makes much practical sense in terms of user experience or security, nor do I think we should really support this usecase explicitly, so I'll close this as "won't fix". Thanks for your understanding.

**Comment by Swiftb0y** [comment]
fyi you can opt into using QtKeychain via the secure storage setting. I'm pretty sure Mixxx on Windows is built with support for it. 
![Screenshot from 2023-06-12 13-50-52](https://github.com/mixxxdj/mixxx/assets/12380386/a5e7c679-5e4d-49f3-ba6a-e244812870fc)

**Comment by ikr83** [comment]
I didn't see it!!! Thanks!
