### ISSUE TITLE
"L" and "P" keys issues

### ISSUE THREAD

**Issue by Gooberpatrol66** [mixxxdj/mixxx#11692]
### Bug Description

1. If I try to do anything related to creating a beatloop it usually causes the L and P buttons to stop functioning and I have to restart the program
2. Sometimes, when starting the program, the L button will open the "Library" entry in the menubar, and pressing it several more times will cause it to go away and cause the track to start playing

### Version

2.3.5

### OS

Guix Linux

**Comment by ronso0** [comment]
> 1. If I try to do anything related to creating a beatloop it usually causes the L and P buttons to stop functioning and I have to restart the program

Does this also happen if none of the beatsize spinboxes has focus? (border highlight)

> 2. Sometimes, when starting the program, the L button will open the "Library" entry in the menubar, and pressing it several more times will cause it to go away and cause the track to start playing

Sounds like the menubar has focus. Do the other menu hotkeys also open the respective menus? F > File, O > Options etc.
After starting Mixxx how did you load a track?

**Comment by Gooberpatrol66** [comment]
>Does this also happen if none of the beatsize spinboxes has focus? (border highlight)

The border of the beatloop is bright green and I can't get it to change from that

>Sounds like the menubar has focus. Do the other menu hotkeys also open the respective menus? F > File, O > Options etc.

Yes. Clicking away does not remove focus

>After starting Mixxx how did you load a track?

File->Load track to deck 1, load track to deck 2

**Comment by ronso0** [comment]
> > After starting Mixxx how did you load a track?

> File->Load track to deck 1, load track to deck 2

IIRC these menu actions are still there to load tracks if you (for whatever reason) don't want to use the Mixxx library (Tracks or Computer feature) or drag'n'drop from a file explorer window to Mixxx decks.
IMO the menu is the most clunky way to do this, even with respetive shortcuts (Ctrl+o, Ctrl+Shift+o).
Why do you prefer this over the library?

However it seems your menu bar keeps keyboard focus after triggering menu ations which is a usability issue, but I doubt it's caused by Mixxx rather by your window manager.

> The border of the beatloop is bright green and I can't get it to change from that

Press Return to move focus to the tracks table. Mixxx hotkeys work as long as the main window has focus (but no spinbox or the searchbar) or the library sidebar or tracks table have focus.

"clicking away" (?) doesn't move focus since you need to explicitly focus a widget in the Mixxx GUI and the only widgets that accept focus are the library sidebar or tracks table, spinboxes, searchbar, dialogs like Track Properties etc.

So if you want keyboard shortcuts to work you should click the library sidebar or tracks table.
