### ISSUE TITLE
Double Click on the track title label in decks crashes Mixxx

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#11802]
### Bug Description

Double click on the title should bring the properties window - the window appears, but stays black and after 2 seconds Mixxx crashes. Hope fast fix because i use Mixxx on a wedding party on friday. 

### Version

2.4 beta 79

### OS

Linux Mint 21.2 Cinnamon

**Comment by ronso0** [comment]
If you can reproduce it reliably please create a backtrace https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

**Comment by ronso0** [comment]
Uff, can confirm. Handling the result of QHash::find in #11764 is wrong, it'll crash with nonexistant property string.
I'm about to fix it.
This reveals another issue: at least LateNight uses `titleInfo` instead of `title` for track labels. Not sure if it was always like that, or if I changed that in the LateNight redesign, and if so why.

@stefan-franz Unfortunately there's no consecutive list of builds in http://ppa.launchpad.net/mixxx/mixxxbetas/ubuntu/pool/main/m/mixxx/, so the last version without this PR is mixxx_2.4~beta~60

**Comment by ronso0** [comment]
> at least LateNight uses titleInfo instead of title for track labels. Not sure if it was always like that, or if I changed that in the LateNight redesign, and if so why.

okay, all skins use this, so I'll simply forward `titleInfo` to the track title field.

**Comment by ronso0** [comment]
fixed by #11804

**Comment by stefan-franz** [comment]
Linux Mint doesn't find an update to download. Not fixed at the moment.
