### ISSUE TITLE
Controller recognized, enabled, but not working

### ISSUE THREAD

**Issue by TheInganno** [mixxxdj/mixxx#11810]
### Bug Description

I got a strange issue with Mixxx and a Hercules MP3 E2 Controller and I am not able to find a solution; I do have the same version of Mixxx on both my desktop and my laptop, both running the same distro (Nobara Linux), both updated to the last software version.
On my desktop, everything is working as it should, no issues at all, but on my laptop the controller is recognized by the app (I can see it appears on the settings page, just like on desktop), and even if it's marked as "enabled", the app is not getting any input from the controller.
I tried launching Mixxx with debug option, but taking a simple look at the log produced on the terminal, I can't see any notable difference from desktop to laptop.
Laptop is 2015ish HP machine with a decent but old hardware. Also, running Mixxx from the Windows 11 partition on the laptop, the controller is working just like on my desktop, so I doubt is something hardware-related.
Anyone can point me in the right direction on how to fix this? I'd love to have it running on my laptop on the linux partition, but my limited knowledge in debugging and troubleshooting isn't helping me that much. 

### Version

2.3.5

### OS

Nobara Linux 38

**Comment by Swiftb0y** [comment]
Hey there, thank you for filling your issue. In order to get to the bottom of this. We would like to inspect your log file. Please use [our guide to find it](https://github.com/mixxxdj/mixxx/wiki/Finding%20the%20Mixxx.log%20file) and then upload it here and we'll see if we can spot anything in the log. Thank you.

**Comment by TheInganno** [comment]
> Hey there, thank you for filling your issue. In order to get to the bottom of this. We would like to inspect your log file. Please use [our guide to find it](https://github.com/mixxxdj/mixxx/wiki/Finding%20the%20Mixxx.log%20file) and then upload it here and we'll see if we can spot anything in the log. Thank you.


Here it is [mixxx.log](https://github.com/mixxxdj/mixxx/files/12327389/mixxx.log)

**Comment by Swiftb0y** [comment]
Thank you. There is nothing suspicious I can spot. Can you check whether the issue still occurs with 2.4 beta and if it still doesn't work please post a logfile from that run?

**Comment by TheInganno** [comment]
Had to build from source since there's no 2.4 beta for Fedora-based system and was my first time building something from source but the wiki was easy to follow; the problem with the controller persist, it's recognized by the settings page but produce no input on the app. I attached the new log [mixxx.log](https://github.com/mixxxdj/mixxx/files/12327634/mixxx.log)

**Comment by Swiftb0y** [comment]
Okay, can you start mixxx with `--controllerDebug --developer` and post the log from that run? I can't spot anything indicative of the issue in the log right now.

**Comment by TheInganno** [comment]
Sorry, I missed your reply, just launched the beta build with those commands you wrote, here's the new log:
[mixxx.log](https://github.com/mixxxdj/mixxx/files/12521856/mixxx.log)
Also, I wanted to point out that it seems to be an issue with the laptop running linux, since in those few days I had the possibility to boot a live USB with an Ubuntu derivative and the issue persist.

**Comment by TheInganno** [comment]
Here we go, I still have to run the build @Swiftb0y suggested, but I managed to produce a log with the desktop system 
[mixxx.log](https://github.com/mixxxdj/mixxx/files/12527476/mixxx.log) (btw i got it with --controllerDebug --developer settings, don't know if it was needed).
Both machines are running the exact same of Nobara Linux, both installed during the same period of time, both updated regularly. As regards libusb, I actually don't know, I'm not an expert user of the command line, but with the GUI-package manager I managed to find a package installed as "libusb1" with version 1.0.26-2.fc38, don't know if this is what you were looking for.
Interesting enough, I tried to plug the controller into an usb-hub, plugged into the laptop, and the console is working with this setup; probably something related with all 3 standard usb ports of my laptop? The ports should be all 3.0 USB ports, according to the manufacturer's website.  
Here's the lsusb -v output with controlled plugged in directly:
https://pastebin.com/VgHXN6Cj
Here's the same line with controller plugged into the hub:
https://pastebin.com/aHzdH3W9

**Comment by Swiftb0y** [comment]
Okay, so another try: https://github.com/Swiftb0y/mixxx/actions/runs/6096805776
The version above will crash on purpose when the controller manager stops polling for the controller (which seems to happen prematurely for you). I want to know why so I need a backtrace from you from the time of the crash. Please see this wiki article for a guide on collecting backtraces https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

**Comment by TheInganno** [comment]
I'm having some troubles running those builds since my distro is fedora based and I can see only a .deb package for linux; I tried a liveusb of both ubuntu and popos but ended up not being able to install the package due to missing dependencies or being able to install but not to install dependencies needed to collect backtraces, any advice?

**Comment by ronso0** [comment]
@TheInganno Are you sure the liveusb OS' you tried are based on Ubuntu 22.04?

**Comment by Swiftb0y** [comment]
> any advice?

Fellow fedora user here, tbh I'd recommend compiling from source. Our guide for fedora should be up-to-date. I'd be happy to guide you when you encounter issues. https://github.com/mixxxdj/mixxx/wiki/Compiling%20on%20Linux#fedora

**Comment by TheInganno** [comment]
@ronso0 yep, I tried with Ubuntu 22.04 LTS and Pop_OS 22.04 but no luck
@Swiftb0y I already had success compiling mixxx from source in the past, just wondering what source should I use in order to obtain the build you wanted me to try

**Comment by ronso0** [comment]
> @ronso0 yep, I tried with Ubuntu 22.04 LTS and Pop_OS 22.04 but no luck

Strange, I just installed the build in a Ubuntu 22.04 VM without issues.

Building from source is preferred if you are able. You need to add @Swiftb0y's repo https://github.com/Swiftb0y/mixxx and checkout the `fix/gh11810` branch.

**Comment by Swiftb0y** [comment]
This branch: https://github.com/Swiftb0y/mixxx/tree/fix/gh11810

You can check that out locally in the cloned repo like this:
```git
git remote add Swiftb0y https://github.com/Swiftb0y/mixxx # you only need to do this once
git fetch Swiftb0y # do this so your local repository knows the state of my upstream repo
git checkout Swiftb0y/fix/gh11810 # do this to checkout my branch
```

**Comment by TheInganno** [comment]
Ok, so I managed to compile the build and I am pretty sure I had success since the sw version in "about mixxx" is fix/gh11810, I followed the guide about backtraces but the program wont crash (maybe I am doing something wrong).
Plugged in the controller, from terminal, gdb->set height 0->run and here I was expecting a crash (?) but nothing happens, the program launches, the controller is recognized by settings but as usual it wont work.

**Comment by Swiftb0y** [comment]
Interesting. Can you share the logfile regardless. Could you also try 2.4-beta and see if the issue persists?

**Comment by TheInganno** [comment]
Here is the log [mixxx.log](https://github.com/mixxxdj/mixxx/files/12565700/mixxx.log); about to download and compile 2.4-beta (btw you already asked me to try that and last time the the issue persisted even in 2.4)

**Comment by Swiftb0y** [comment]
> btw you already asked me to try that and last time the the issue persisted even in 2.4

Sorry, I wasn't sure if I did. Then we can skip that step. The issue is also still in the logfile. It seems my changes to make mixxx crash at the desired point didn't suffice. I'll push a new commit soon.

**Comment by Swiftb0y** [comment]
I added another commit on https://github.com/Swiftb0y/mixxx/tree/fix/gh11810 that tries to crash mixxx. Please try that and see if works. I'm sorry I'm rather short on time right now so I wasn't able to confirm whether the additions actually cause a crash as desired. In either way, please upload the new logfile again.

**Comment by TheInganno** [comment]
Don't worry at all about being short on time, I have no rush at all and I am extremely grateful to being somehow of help in fixing this issue, I do also take some time to do everything due to work and personal stuff. 

Anyway, I managed to compile the new build; interesting enough, this build crashes on startup even if the controller is not plugged in. I collected backtraces with console plugged in anyway https://pastebin.com/raw/unf73yY9 (I hope I did it right) and here's the log file too [mixxx.log](https://github.com/mixxxdj/mixxx/files/12568191/mixxx.log)

**Comment by Swiftb0y** [comment]
Thank you. That was very helpful. So the thing I tried to debug via the crash was actually unrelated and not part of the issue. I'm a little lost now myself. I removed the intentional crashing code and instead enabled extra debug info in the mapping (I assume the mapping file is "Hercules-mp3e2-compat.js") and pushed to the branch again (you probably need to `git pull --force`). Can you try that and send me the log again. There should be a bunch of `******* Incoming Data from controller` messages.

**Comment by TheInganno** [comment]
Tried that new build, in the newly generated log I cannot see those Incoming data from controller messages, anyway here it is! [mixxx.log](https://github.com/mixxxdj/mixxx/files/12569009/mixxx.log)

**Comment by Swiftb0y** [comment]
did you make sure to start with `--controllerDebug`? Did you try to create some incoming data by interacting with the controller a bit?

**Comment by TheInganno** [comment]
Of course I totally forgot about that line while starting up mixxx, my bad, sorry. Here's the log with this launch command enabled [mixxx.log](https://github.com/mixxxdj/mixxx/files/12569701/mixxx.log)

**Comment by Swiftb0y** [comment]
Did you try to create some input? Previously the log sometimes contained lines starting with `Debug [Controller]: DJ Control MP3 e2 : t:`. This doesn't seem to be the case here so I'm not sure whether mixxx is really not receiving any input or if its just not passing it along to the mapping.

**Comment by TheInganno** [comment]
Yep, I interacted for about 30s by pressing almost all type of input devices on the controller; I also just checked out that the controller was enabled by the settings page and it was.

**Comment by Swiftb0y** [comment]
Okay, I have no idea what the problem is. Only thing that might work now is a `git bisect` (there are plenty of tutorials on the internet), but since that involves testing which version works and which doesn't it can only be done by you. It'll also be time consuming because you'll have to do lots of testing and lots of compiling, but its the only way I can see how we can get to the bottom of this now...

**Comment by Holzhaus** [comment]
Have you verified that the OS actually reviews MIDI data? You can list MIDI device names using `aseqdump -l` and then start listening using `aseqdump -p "my device name"`. It should "note on/off" events when you press buttons on the controller.

**Comment by Swiftb0y** [comment]
This is not a midi controller unfortunately. It seems to be sending Midi data, but its using a bulk endpoint.

**Comment by Swiftb0y** [comment]
And yes, it has sent data in the past, some of the earlier logs contained debug output with messages from the controller. I'm not sure why thats not the case for the later ones.

**Comment by loziniak** [comment]
Hello. I have the same problem.

My console output for `$ mixxx --controller-debug --developer` for normal user: [mixxx_terminal.txt](https://github.com/user-attachments/files/16635602/mixxx_terminal.txt)
and for root (with deleted config folder): [mixxx_terminal_root.txt](https://github.com/user-attachments/files/16635613/mixxx_terminal_root.txt)

I also did some USB snooping with Wireshark (as described [here](https://github.com/mixxxdj/mixxx/wiki/Reverse%20engineering#observing-midihid-messages-with-other-dj-software)), and it resulted in this log: [hercules4.pcapng.zip](https://github.com/user-attachments/files/16635648/hercules4.pcapng.zip)

It has shown outgoing communication is fine (try wireshark display filter `usb.device_address==13 && usb.endpoint_address.direction=="OUT"`), but only incoming messages (filter `usb.device_address==13 && usb.endpoint_address.direction=="IN"`) were the two repeating throughout a runtime of mixxx with very high frequency:
![obraz](https://github.com/user-attachments/assets/e8ec57f0-88bb-483e-b366-9fa0f126310f)
![obraz](https://github.com/user-attachments/assets/4f4a7cec-3ac7-449a-87a8-0acd15a751be)

no hdjd or kernel driver
no access rights changes, no udev rules installed (seems USB is accessible, because Mixxx can send data to controller, also there are no warnings about access in logs, also it does not work with root as well)
controller is on MIDI channel 1, jog wheels are enabled

lsusb output (device address is different, because I reconnected a controller several times since then):
```
$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 0c45:6717 Microdia Integrated_Webcam_HD
Bus 001 Device 005: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 006: ID 0a5c:5832 Broadcom Corp. BCM5880 Secure Applications Processor Smartcard reader
Bus 001 Device 021: ID 0458:6001 KYE Systems Corp. (Mouse Systems) GF3000F Ethernet Adapter
Bus 001 Device 022: ID 06f8:b105 Guillemot Corp. DJ Control MP3 e2 [Hercules DJ Control MP3 e2]
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
$ uname -a
Linux latitude5580 6.6.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:57:10 UTC 2024 x86_64 GNU/Linux
$ LC_ALL=C pacman -Qi libusb
Name            : libusb
Version         : 1.0.27-1
[....]
$ amidi -l
Dir Device    Name
cannot determine device number: Inappropriate ioctl for device
```

**Comment by loziniak** [comment]
I thouht that maybe if `hdjd` works, then some initialization is needed for controller to send data? We could perhaps ask @nealey about it...

**Comment by loziniak** [comment]
@TheInganno have you tried connecting through a USB Hub? Some people report a success with USB3 hubs:

https://mixxx.discourse.group/t/solved-cant-make-hercule-dj-control-mp3-e2-work-under-linux/22920
https://mixxx.discourse.group/t/controller-issue-buttons-lit-up-but-nothing-happens-when-pressed/21809
https://mixxx.discourse.group/t/hercules-mp3-e2-everything-seems-fine-but-no-input-linux-mint-20-2/22786

**Comment by nealey** [comment]
> I thouht that maybe if `hdjd` works, then some initialization is needed for controller to send data? We could perhaps ask @nealey about it...

Hi. I wrote the MP3e2 "bulk" driver for Mixxx but I haven't touched the code in years. I later created hdjd as a replacement for what at the time was a very old and increasingly broken kernel driver. 

The MP3e2 I have requires no setup at all, it just starts streaming MIDI events over a USB Bulk endpoint as soon as it's plugged in. The Wireshark dump is super curious. I'm not sure what's going on there.

The DJ 4Set Guillemot sent me acted similarly to what this bug is describing. I gave up on making it work, figuring it needed some initialization code. But one day, someone sent me a one-line patch to hdjd that consisted of nothing more than the correct endpoint, and this was all the 4Set needed.

It's possible that Guillemot changed the endpoint on the MP3e2. I would encourage anybody who understands things enough to run that Wireshark sniffer on every endpoint exposed by the controller when you plug it in, and see if you can find one that sends events when you press and release buttons on the controller. If you can then send me the device numbers and the endpoint you used, I'll add a patch to hdjd that should make the controller work. And probably if you open a specific bug (or, better, merge request) against mixxx, you can get the code added in there too, so you don't need to run hdjd first.

**Comment by loziniak** [comment]
Thanks! I actually had a success with a USB Hub, so it seems the controller has no support for USB3. Perhaps that means there's nothing else we can do?

**Comment by nealey** [comment]
> Thanks! I actually had a success with a USB Hub, so it seems the controller has no support for USB3. Perhaps that means there's nothing else we can do?


That is so strange! But enough people have reported this all a fix, I have to accept it must be real.

**Comment by loziniak** [comment]
I tried an old USB hub the other time (could be even USB2 - only), but lately I bought a new one (USB3 + USB2), and it works as well, also on USB3 port.
