### ISSUE TITLE
Waveform playmarker position shown outside loop, while track is inside loop

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11836]
### Bug Description

In the screenshot below, you see the blue actual playmarker position outside the active green loop: 
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/86cb1a93-7f59-4653-8c10-79f7e634e687)
Above the loop size was 15ms and the refresh interval 60fps (16,6ms).

The problem increases with lower framerate (here 20fps - 50ms):
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/61c1174c-8be3-46d2-a0b9-70430949a5f1)

### Version

2.4.0beta

### OS

Windows11

**Comment by m0dB** [comment]
I think this can be done easily by adding `loopInfo.startPosition` and `loopInfo.endPosition` from the `EngineBuffer`'s `m_pLoopingControl` to the arguments to the `m_visualPlayPos->set(...)` call in `EngineBuffer`.

In `VisualPlayPosition::getAtNextVSync` and `VisualPlayPosition::getPlaySlipAtNextVSync`, we can than adjust the predicted `playPosition` and `slipPosition` accordingly.

The code to do the adjustment is in `LoopControl::adjustedPositionInsideAdjustedLoop` which doesn't seem to use any member variables to it could be moved to a static method.

**Comment by ronso0** [comment]
Yeah, might work. That's what I meant by "copying engine code to waveforms" 😉

**Comment by m0dB** [comment]
Right, but I mean that this can be done without any actual code duplication. There are other ways to do this (e.g. replicating the entire loop control at the UI side which would act on the some control parameters) that would certainly involve a lot more "copying engine code to waveforms" 😅 

@JoergAtGithub maybe you can give it a try with these suggestions? Otherwise, I can have a go at it. But I assume this is not a blocker for 2.4, so no hurry, right?

**Comment by ronso0** [comment]
Yep, no blocker, it's 'always' been like this.

Great if it's as easy as you say 👍

**Comment by daschuer** [comment]
@JoergAtGithub: Can you confirm you have taken the screenshot while playing and that is does not happen when paused? 
Than it is the mentioned side effect of quantization of loop cycle, audio buffer and refresh rate. 

I am not sure if the mentioned solution by m0dB is worth the work, because this will introduce other issues like waveform moving backwards or stopping. Just like wheels in movies turning backwards in certain speeds.

**Comment by JoergAtGithub** [comment]
PR is here: #11840
LoopControl::adjustedPositionInsideAdjustedLoop wasn't suitable here, because we don't move the loop itself here. A simple modulus/remainder operation did the job.
