### ISSUE TITLE
library interaction controller COs not working on QT6 / noQML build

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/mixxx#11854]
### Bug Description

I have controller encoders bound to navigate the library -- up, down, load track, change focus, etc. In a QT6 build, these bindings stop working and have no effect. I believe these COs emit keyboard events to cause the UI changes? That might be what broke

### Version

HEAD

### OS

Ubuntu 22.04

**Comment by ywwg** [comment]
Added a new QT6 label because I suspect that will be useful :)

**Comment by ronso0** [comment]
many (all?) library controls are guarded by 
Qt version < 6.0 https://github.com/mixxxdj/mixxx/blob/main/src/library/librarycontrol.cpp because Qt6 was assumed to build the Qml library, but does now build the legacy interface hy default?
So replacing these guards with #ifdef QML, if that exists, would enable them again.

**Comment by ronso0** [comment]
It's `#ifndef MIXXX_USE_QML`
Dunno why that was not changed in #11608 -> 3d1c7a69379362867bb5b8e2e8dbbb0893db88dd

Changing the remainders is a no-brainer. Is someone already fixing this?

**Comment by fwcd** [comment]
Not sure, but I stumbled upon this and couldn't find anything, so I opened #11877. I've only updated the controller-related `#if`s, since I wasn't sure about the others.
