### ISSUE TITLE
Why do waveform types have different visual gains?

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12115]
![image](https://github.com/mixxxdj/mixxx/assets/5934199/1adc2651-8e6a-42a7-840f-95daa4c35ad2)
![image](https://github.com/mixxxdj/mixxx/assets/5934199/ffa11872-299d-420d-b20e-3add6afc94a5)
![image](https://github.com/mixxxdj/mixxx/assets/5934199/a451e57c-cf02-4dbe-8adb-dc6f0bc55930)
![image](https://github.com/mixxxdj/mixxx/assets/5934199/76f57cfa-a94d-411d-9b92-b9211931d271)

Is this to be expected?
Anyhow, if I want to test waveforms I'd also need to adjust the visual gain to make the comparable.

**Comment by daschuer** [comment]
I think we can consider this a bug.

**Comment by m0dB** [comment]
I agree. The cause must be in how the amplitude is calculated by combining the high/mid/low values vs the real amplitude. So there might be an inherent and unavoidable difference but it shouldn't be this big. I will have a look when I have a moment.

**Comment by m0dB** [comment]
First of all, note that when I implemented this for the new waveform types, I just based it on the existing implementations, so I am not 100% sure what the original thought behind all this is.

The waveform data contains values for _low_, _mid_, _high_, and _all_ . The RGB waveform renderer combines the _low_ , _mid_ and _high_ values to calculate the total amplitude: _combined = sqrt(low^2+mid^2+high^2)_, apparently based on the assumption that this value will be close to the _all_ value. This is unfortunately not the case. I plotted _all_ (x axis) against _combined_ values (y axis):

<img width="708" alt="Screenshot 2023-10-21 at 22 00 08" src="https://github.com/mixxxdj/mixxx/assets/79429057/8de68222-4aff-444c-8880-ba749874364c">

In the best case, they are equal, but generally the combined value is lower. I don't know how the _low_, _mid_ and _high_ values are calculated but clearly not in a way that makes the above assumption hold.

So the obvious question is: why don't we use the _all_ value for the amplitude that we draw, and the _low_, _mid_ and _high_ only to calculate the color? Because with the current implementation, the amplitude adapts to the low, mid and high gains, which is really nice.

Now, I think I have a way to improve this, I will try something and let you know.

**Comment by ronso0** [comment]
Thanks for looking into this!

**Comment by m0dB** [comment]
I have generated another plot, based on more data.

<img width="752" alt="Screenshot 2023-10-22 at 00 31 35" src="https://github.com/mixxxdj/mixxx/assets/79429057/fc5c8ff5-35b1-4822-9cc7-2a4b952238c5">

Furthermore, I see that the amplitude as drawn is scaled at 0.575 times the scaling of the simple waveform (again, this comes from the legacy code). Correcting that should already bring the amplitudes much, much closer. 

But I also see the reason for this factor. The range of the _low_, _mid_, _high_ and _all_ is 0..255. So, in the simple waveform, the drawing scale is halfBreadth / 255. (halfBreadth = half the widget height).

In the case of combining _low_ _mid_ and _high_ with _combined = sqrt(low^2+mid^2+high^2)_ , the maximum value of _combined_ is sqrt(255^2+255^2+255^2) =~ 440, and that is what we are scaling with, halfBreadth / 440.

Now, I have to say, I personally like to have a bit of headroom in the drawing. But the way that occurs now doesn't seem to be intentional. In fact, it all seems a bit flawed, conceptually.

**Comment by m0dB** [comment]
I came up with a simple solution, without having to change the code much.

https://github.com/mixxxdj/mixxx/pull/12205

**Comment by m0dB** [comment]
And with that I discovered the "visual gain" spinbox in the preferences, something I never needed before 😄
