### ISSUE TITLE
Mixxx seeking access permission form iTunes Media folder on every launch

### ISSUE THREAD

**Issue by AlrightHector** [mixxxdj/mixxx#12137]
### Bug Description

Each time I launch Mixxx 2.4 beta it is seeking access permission to the iTunes Media folder.It's not retaining permissions.

### Version

2.4

### OS

Mac OS 10.14.6

**Comment by fwcd** [comment]
Interesting, I didn't even know that we still supported macOS Mojave. Looks like 2.4 still supports macOS all the way back to Sierra (10.12).

That sounds a bit like #11552. Is "Full Disk Access" enabled for Mixxx in your settings?

**Comment by fwcd** [comment]
By the way, the 2.4 snapshot builds from the website are quite outdated and IIRC do not include #11936 yet.

Could you try e.g. [this build](https://github.com/mixxxdj/mixxx/actions/runs/6411366768)? (scroll down and download `macOS Intel DMG`)

**Comment by AlrightHector** [comment]
Thanks, the message doesn't appear for this build.

**Comment by fwcd** [comment]
Yep, that build was unsandboxed and wouldn't have had the issue anyway, sorry...

Could you try the following build? https://github.com/mixxxdj/mixxx/actions/runs/6562071482

**Comment by AlrightHector** [comment]
This build has the same issue, requesting permission. I've tried granting
full disc access, but the issue remains.

**Comment by fwcd** [comment]
Hm, that's annoying. So I'll assume that #11552 isn't fixed after all...

**Comment by fwcd** [comment]
I _think_ the issue was introduced by this PR a while back (cc @uklotzde):

- https://github.com/mixxxdj/mixxx/pull/3761

If you have some time to spare and would like to dig into this, you could try [building Mixxx](https://github.com/mixxxdj/mixxx/blob/main/README.md#building-mixxx) before:

```sh
git clone https://github.com/mixxxdj/mixxx.git
cd mixxx
git checkout 9e974cdb && git cherry-pick 59168913 e9223294 cf8e5a44
source tools/macos_buildenv.sh setup
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMACOS_BUNDLE=ON -B build
cmake --build build
cd build
cpack -G DragNDrop
```

and after that PR:

```sh
git clone https://github.com/mixxxdj/mixxx.git
cd mixxx
git checkout c9f52dc1 && git cherry-pick 59168913 e9223294 cf8e5a44
source tools/macos_buildenv.sh setup
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMACOS_BUNDLE=ON -B build
cmake --build build
cd build
cpack -G DragNDrop
```

and check whether that confirms the suspicion, i.e. that only the second build has the issue. (The cherry-picks are https://github.com/mixxxdj/mixxx/pull/4774 and https://github.com/mixxxdj/mixxx/pull/12138, which are needed to enable app sandbox in unsigned builds)

I don't have an older Mac around right now unfortunately, so I can't test this right now.

**Comment by m0dB** [comment]
@fwcd I can test this on Monterey. Would that be helpful or does it only affect older versions of macOS?

**Comment by fwcd** [comment]
Sure, that would be helpful

**Comment by fwcd** [comment]
I can consistently reproduce this on another Sonoma machine today after upgrading Mixxx to the latest snapshot... even after deleting `sandbox.cfg` and after granting full disk access. I suspect a reason why I didn't encounter the issue on the other machine was that I kept my tracks in `~/Music` (which might have special sandbox privileges?) instead of a different "non-standard" subfolder of home. I'll have to investigate once I find more time...

**Comment by fwcd** [comment]
Note that the warning seems to be bogus, Mixxx has no issues reading the tracks even when clicking cancel. Not sure if that could be since I am running an unsigned build, but in general I don't really understand how the sandbox works, since browsing the entire file system in the "Computer" section of the sidebar is not an issue either...

**Comment by fwcd** [comment]
2.3 doesn't have this issue and the older 2.4 alpha snapshots from 2021, specifically those before #3761, are (sadly) no longer hosted on https://downloads.mixxx.org. The newer 2.4 snapshots all have the issue.

**Comment by uklotzde** [comment]
A missing or lost sandbox argument should be easy to fix. But unfortunately that could only be done by someone who has access to macOS as their development platform.
