### ISSUE TITLE
Reset tapped BPM button

### ISSUE THREAD

**Issue by axelkar** [mixxxdj/mixxx#12209]
### Feature Description

It is possible to right-click the track in the library and select `Adjust BPM` > `Reset BPM` but it's very inconvenient especially when someone accidentally taps the BPM button and doesn't know how to reset it.

Btw, can the GitHub discussion tab be enabled as the Zulip instance doesn't like my email server and I'd like to ask for help with some things related to the control object system?

**Comment by axelkar** [comment]
Oh and what's the status on 2.4-alpha(?) vs 2.5 and the newest GitHub release 2.3.6?

**Comment by ronso0** [comment]
> It is possible to right-click the track in the library and select Adjust BPM > Reset BPM

That is also available in the decks' track menu (right-click any track label).
Double-clicking the labels brings up the Track Properties which have a BPM tab with all related controls:
![image](https://github.com/mixxxdj/mixxx/assets/5934199/138648fe-679e-49d0-8721-82c00d9dcc06)

I think we need to make the deck context menu more discoverable, and the first thing coming to mind is a simple hover effect, as used in #11755

Since I also a few times ran into this issue (accidentally set track BPM) I'm very much in favor of replacing the BPM tap button (set track BPM) with a **rate** tap button (tap playback speed), see #12104.

**Comment by ronso0** [comment]
> Zulip instance doesn't like my email server

You can login with Github for example. Doesn't that work for you?

**Comment by axelkar** [comment]
> You can login with Github for example. Doesn't that work for you?

That worked! Thanks.

**Comment by ronso0** [comment]
> very inconvenient especially when someone accidentally taps the BPM button

That is fixed by #12104.

This is the actual issue
> I think we need to make the deck context menu more discoverable

so users find the Re-Analyze actions.
The hover effect I proposed can be applied to skins that have hover effects in other places.
I think some kind of Quick Start Guide, or tutorial (mini walkthrough) would be more helpful.
