### ISSUE TITLE
Changing the waveform overview type after changing the main waveform type resets the main waveform type

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12226]
### Bug Description

I set the main waveform type to "Simple (GLSL)" and Ok the preferences.

Then I go back in, and select "Filtered (GLSL)" for the main waveform type, and it changes to the newer non-semitransparent stacked RGB style. (I know "stacked" and "RGB" relate to other waveform styles, but I really don't know how else to simply describe the new style!)

But I then change the waveform overview type, and the main waveform type changes style from "Filtered (GLSL)" to something else.

I Ok the preferences, then I reopen the preferences and the option main waveform type has changed to "RBG (GLSL)"

This happened regardless of what the initial main waveform type is.

Arguably related to #9745 in some way

### Version

2.5-alpha-137-gc2f2f64891 (main)

### OS

Arch btw

**Comment by ronso0** [comment]
Yes, I noticed this as well recently.

This is part of  meta issue #7440
All waveform settings are applied **instantly** and (supposed to be) saved to the config, i.e. without having to Apply, **except** the two Caching checkboxes.

So, this is a UX clash between
* convenient instant preview for the waveform type  (it's not a true _preview_ since Cancel does not restore the previous type, i.e. the type that was confirmed with Apply/Ok)
* consistent Apply/Ok/Cancel behaviour across all preference pages

Furthermore, overview types are realized via dedicated overview widgets. Changing the type requires the skin to be rebuilt.
Hence, by attempting to provide the same 'instant' preview for overviews, the **skin is reloaded**.
The bug here (which should be fixable without a bigger reafctoring IMO) is that the waveform type falls back to the last applied type (even without updating the waveform selector) when the skin is reloaded.

I'll look into it.

**Comment by ronso0** [comment]
Fixed in #12231

**Comment by mxmilkiib** [comment]
This appears fixed.

I did manage to fairly quickly make Mixxx crash on changing each option in quick succession, but that's another issue.
