### ISSUE TITLE
scratching waveform backwards with a saved, active loop ahead temporarily jumps to that loop (visuals only)

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12274]
* create a hotcue loop
* jump back a few bars
* play
* ativate loop (catching loop)
* drag waveform forwards = visuals as expected
* drag waveform backwards = visual position jumps to loop (audio is not affected)

https://github.com/mixxxdj/mixxx/assets/5934199/0115009a-7463-4f45-a304-3de6acaa7db1

### Version

2.4-beta-216-g5454b94b71

### OS

Ubuntu Studio 20.04 / X11 / xfce 4.14 / Qt 5.12.8

**Comment by ronso0** [comment]
I reproduced with a regular (temp, unsaved) re-loop and, while it also jumps, it did _once_ jump while scratching **forward** :man_shrugging:

**Comment by Swiftb0y** [comment]
Potentially related, just didn't bother reporting it: When you scratch with the mouse on the overview waveform and you scratch past the loop, the engine essentially repeatedly tries to scratch to that position past the loop, which it can obviously never reach due to the loop. 

[Screencast from 2023-11-08 12-50-25.webm](https://github.com/mixxxdj/mixxx/assets/12380386/d110c72b-bdea-4bb4-b7f4-f0fdb05347bb)

**Comment by Swiftb0y** [comment]
I can also confirm your original exact issue.

**Comment by ronso0** [comment]
@JoergAtGithub Maybe a regression caused by #11840 ?

**Comment by ronso0** [comment]
Also, I did not yet test with 'real' scratching, only with the waveforms.

**Comment by Swiftb0y** [comment]
If with "real" scratching you mean via a controller or DVS then I'm pretty sure its unaffected.

**Comment by JoergAtGithub** [comment]
I can confirm both issues, the one reported by @ronso0 is indeed a regression of #11840. The issue reported by @Swiftb0y affects also earlier commits (seen with 679e4dcddbfff209f35e7a05df24b4b51719a9e7 the commit before merging #11840), I moved in a dedicated issue therefore.
