### ISSUE TITLE
Vinyl passthrough sound is distorted

### ISSUE THREAD

**Issue by tbazant** [mixxxdj/mixxx#12398]
### Bug Description

Into my PC's AUX, I connect output from a real turntable. I configure `Sound Hardware -> Input` and map channels 1&2 as Vinyl Control 1. 
![obrazek](https://github.com/mixxxdj/mixxx/assets/2240174/de872803-9d84-4e41-a2d1-6ef6b3d7be62)

In the `Vinyl Control`, i boost the input signal and leave Serato as the Deck 1 `Vinyl Type` - just because there is no `Passthrough` option.
![obrazek](https://github.com/mixxxdj/mixxx/assets/2240174/bb85a9a7-53e4-495e-ab7b-367d2b21a36d)
After I enable the `PASS` button in desk 1, I can hear the music from my turntable, but it is weak and distorted compared to a clean vinyl sound played directly to HW amplifier. From my findings it is obvious that:
* turntable signal boost does not work for PASS mode
* Serato (or any other) vinyl type is not the right type to select
* or I'm doing thing the wrong way and nee a good advice how to setup things to make the audio signal cleanly pass through Mixxx, optionally adjusted by the effect/mixer controls.

### Version

2.3.3

### OS

Debian Linux

**Comment by ronso0** [comment]
Neither VC nor passthrough work with phono level, you need pre-amps or a sound card that can handle phono level.
RTFM ; )
https://manual.mixxx.org/2.3/en/chapters/vinyl_control#what-do-i-need-to-use-it

**Comment by Swiftb0y** [comment]
Or optionally a turntable that has a phono pre-amp built in (most modern ones do afaik),
so if yours is not ancient, there may just be a simple switch somewhere on your turntable to enable the built-in one.

To clarify: this is not a bug because its not possible/realistic for mixxx to handle this. Phono signals are incredibly quiet and if you just put that into a regular line-level DAC such as your soundblaster, the DAC will introduce so much noise that the turntable signal will get drowned out. If you then boost the signal, it'll of course amplify the original signal as well as the noise since its the same signal once it reaches the Computer. There is no software way to convert a noisy signal to a clean signal while retaining the information needed for vinyl control. You'll need proper hardware (a phono-preamp) to handle phono signals.

**Comment by ronso0** [comment]
> Or optionally a turntable that has a phono pre-amp built in (most modern ones do afaik),

One down-side of this (entirely off-topic): if you like to do a slow, steady brake by turning off the turntable, the pre-amp will also turn off and stop output before the platter stopped.

**Comment by tbazant** [comment]
OK, thanks for info. I connected a new DUAL turntable with pre-amplifier. Audio signal is much louder now, still it's distorted compared to straight cable connection/MP3 files played from Mixxx. The distortion is most remarkable in high pitch tones/voice.
I emphasize that i'm talking about passthrough and not tomecode vinyls.

**Comment by ronso0** [comment]
If it's a permanent distortion it may be due to clipping. Does it clip in Mixxx? (warch the VU meters of that deck)
Make sure you have boost configured in your sound device manager.

Or it's simply buffer underruns and you need to increase the latency (audio buffer).

**Comment by tbazant** [comment]
> If it's a permanent distortion it may be due to clipping. Does it clip in Mixxx? (warch the VU meters of that deck) Make sure you have boost configured in your sound device manager.
> 
> Or it's simply buffer underruns and you need to increase the latency (audio buffer).

It's a permanent loss of quality but not clipping. High Ssss-sounds are affected most. How does this passthrough work BTW? Mixxx needs to digitalize the vinyl audio input to be able to process it with effects and mixer? If yes, can these digitalize parameters be configured or are they hardwired? I'll try the audio buffer, thanks for the advice.

**Comment by Swiftb0y** [comment]
The audio is already digitized by your soundcard. Mixxx does not have much influence on that process (except the audio samplerate, but if that is incorrect it usually doesn't work at all or your sound is pitched and sped up / slowed down, nothing like the distortion you are discribing). An audio-buffer thats too small could be culprit, but that also creates a different sounding distortion from what you're likely describing. The vinyl passthrough just takes that input audio signal and forwards it back to the output (essentially, of course I'm explaning it a little simplified). Are you sure the issue is only related to mixxx? For example have you tried recording the turntable signal in a different software such as Ardour? Does the same distortion apply there too?

**Comment by tbazant** [comment]
I tried recording the turntable audio in Audacity and it is completely clean, comparable to playing MP3's. Should I try Ardour besides Audacity? Is there a difference?

**Comment by tbazant** [comment]
So.....Mixxx is doing a good job. I tried several LPs and for the new ones, the distortion was minimal to zero, so the testing SP was to blame. Thanks for your patience once more.
