### ISSUE TITLE
Beatloop size: keep loop end, adjust loop start in UI by right-clicking on up/down buttons?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12610]
### Feature Description

One can adjust the loop-out marker forwards and back by left clicking on the up and down arrows next to the size number.

How about moving the loop in marker back and forth by right clicking the same buttons? 

Instead of showing a right-click context menu. 

This would allow for more creative opportinuties.

**Comment by ronso0** [comment]
Sounds reasonable.

Note for all those who want to tackle this:
IMO squeezing this into `WBeatSpinBox` (used for both `beatloop_size` and `beatjump_size`) is rather complex since it can't be done with how the `size` control value change is currently transmitted to LoopingControl.
First obstacle: both button up/down clicks and Up/Down keyboard presses call `WBeatSpinBox::stepBy`, there one would somehow need to check if Shift is pressed.
Second, LoopingControl would need to know about "keep loop end position".

IMO, making this available both in the GUI and for other controls (controllers), adding a `loop_halve/double_keep_end` would be the way to go.
I.e. separate the Up/Down buttons from the spinbox.
Related: #11969

**Comment by ronso0** [comment]
Fixed by #12745 isn't it?

Feel free to reopen in case I missed some aspect.
