### ISSUE TITLE
origins of effect Meta knob arcs are not consistent relative to their default positions

### ISSUE THREAD

**Issue by nvdl** [mixxxdj/mixxx#12634]
### Bug Description

Mixxx 2.4.0-beta
Git Version: 2.4-beta-347-gc323d0cd54
Platform: Linux x86_64
OS: Debian 11

Some knobs do not draw the delta ring relative to their default position.

![Screenshot from 2024-01-23 20-06-51](https://github.com/mixxxdj/mixxx/assets/3097827/1268389c-e0f8-4528-ac5e-7be70b67ef2d)
![Screenshot from 2024-01-23 20-07-18](https://github.com/mixxxdj/mixxx/assets/3097827/46060fdd-aef0-44b3-a820-ba593a58083a)

"Echo", "Moog Filter" and "Balance" in the above shots do not draw the ring relative to the default (minimal/no-effect) position.

**Comment by ronso0** [comment]
Yes, these are still dumb knobs currently. Arc origin is set in the skin (static) to either center, left or right.

To make them dynamic, i.e. aware of the effect's default Meta parameter we'd need to
* add `WEffectMetaKnob`, derived from `WKnobComposed`
* listen to `EffectSlot::effectChanged` in order to
* get the manifest of the loaded effect, read & store default Meta parameter
* adjust `drawArc()` to make use of it

Nice little weekend project for Mixxx 2.4.x : )
