### ISSUE TITLE
Double click on touch on Windows

### ISSUE THREAD

**Issue by bencejuhaasz** [mixxxdj/mixxx#12848]
### Bug Description

On Windows, pressing a button via a touch screen sends multiple clicks continously until held. This makes toggle buttons unusable, as they only get toggled if held for the right time. A touch should send a single click. 

### Version

2.4

### OS

Windows 11

**Comment by ronso0** [comment]
You need to configure this in Windows, probably Control Panel -> (Pen and) Touch.
E.g. long press can trigger a right-click after N millis, or be press-and-hold like with a regular click mouse.

Closing this since it's not Mixxx' responsibility, also this seems to work well on other touch devices, e.g. RPi with touchscreen.
