### ISSUE TITLE
Color played tracks ... invisible when working with coloured tracks

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12907]
### Bug Description

- When working with colors than gives the new feature  "color played tracks" a very small distinction, it is more the text change that can be spotted. 
- Is it possible to make an settings-item to enable/disable "color played tracks" or at least to be able to choose the used color, preferable a color that is not already in the used palet.
- The text-blurring is difficult for people with older eyes or who have a visual problem.

-> I'm testing the main from 29/2/2024 on Win10 / Win 11

### Version

2.5-alpha-255-g2d2d5f304b

### OS

Win10 / Win 11

**Comment by ronso0** [comment]
Yes, that can be customized (sort of) via the skins' stylesheet, for exampe here
https://github.com/mixxxdj/mixxx/blob/2d2d5f304b97a67de325061f6183e0aabbc3a2f6/res/skins/LateNight/style_palemoon.qss#L2597

We could make it configurable in the Library prefrences
a) a brightness factor?
not that easy since we'd need to get the qss font color, and IIUC that's difficult or even imposible 
b) an explicit color?
should be easy, but probably needs to be adjusted when switching skins

For #12744 I've also considered setting a font style, e.g. make it italic or cross-out tracks, but since the library font can be customized it's not guaranteed these font properties are available.

Any other ideas how mark tracks while maintaining a sufficient font contrast?

**Comment by daschuer** [comment]
This means we need to make this feature at least optional. This way we have no regression, because the feature can be disabled if causing harm

**Comment by Eve00000** [comment]
I understand and appreciate the goal of marking played tracks, but screens are getting smaller (for portable reasons now mostly 13") and when some comment is added to a track (version or fi 'explodes at 1:24') than it it very difficult. 
The audience wants some tracks (hits of the moment) to be played several times, (preferable different remixes), so the comments etc must remain readable.
I found the  'played'-checkmark giving enough information (placed left) 
I would prefer not to play around with brightness. There are already a lot of lights flashing around (on the audience) so everything must remain simple and quiet. 
It's no fun to have to take your glasses to read the comments ;-)

**Comment by ronso0** [comment]
There is no doubt that greying out info in a table impairs accessibility, thanks for your perspective though!

#12912 makes greying out optional (opt-out).
If you have other ideas how to mark played tracks kee'em coming!

Re you use case on small screens:
on regular/large laptop screens (talking about 13-15") the :heavy_check_mark: may be overlooked. There's already a lot of info to consider when browsing tracks, BPM, cover art hint, artist/title of course, and the comments. , I overlooked it numerous times.
So even though greying out every column except comments might work in your case, I don't think that's general solution either.

**Comment by Eve00000** [comment]
I'm using the standard Latenight - Palemoon.

An idea...
When browsing in the library, selecting a part (field) of a track creates a white border on a gray background with highlighted white letters. This is very readable and clear. 
Maybe you can try something with creating a border around the complete line? (with maintaining the original trackcolor )

You're working on the display of 'played tracks', is it hard to do something with 'currently loaded tracks'?

**Comment by ronso0** [comment]
>  'currently loaded tracks'?

Yes, that requires a new TableItemDelegate (like BPM, Played, cover, color etc.).
This tracked in #9418.
