### ISSUE TITLE
Waveforms break when using a derivative of LateNight

### ISSUE THREAD

**Issue by morgannunan** [mixxxdj/mixxx#13434]
### Bug Description

I have a custom theme based on LateNight, and in 2.5 the waveforms disappear. This is also true of the built-in 64-sampler version of the theme.

I have a fix on my fork of Mixxx, but I'm not actually sure how to open a pr from my fork to this version, or if that's even the correct way to do this. Please advise.

### Version

2.5

### OS

Ubuntu 22.04

**Comment by ronso0** [comment]
Anyway, I wonder why it broke for you, I switch between 2.4 and 2.5 all the time.
Just tested: 2.5 with the skin resources of 2.4 shows me waveforms as expected.

**Comment by morgannunan** [comment]
Did you switch to LateNight (64 Samplers)?

**Comment by ronso0** [comment]
Yes. I'm running the 2.5-beta binary with the 2.4 res/ directory.

Where did you put that modded skin?
**/usr/share/mixxx/skins**
or
**~/.mixxx/skins** (/home/[username]/.mixxx/skins)

**~/.mixxx** is recommended for downloaded/user skins (that are created in a way that they work without references to official skins).

**/usr/..** is recommended for skins that reference files of existing (built-in) skins. Pay attention to not just mod an existing skin but copy & rename an existing skin directory, otherwise that might be overriden when installing another Mixxx version. https://github.com/mixxxdj/mixxx/wiki/Creating-Skins#change-an-existing-skin
In this case you can actually remove all templates from the mod directory that you don't intend to change. For example, if you create a LateNight mod with a stripped mixer, you'd copy /usr/../LateNight to /usr/../LateNight_StrippedMixer and could remove all irrelevant files, i.e. everything except skin.xml, mixer.xml and the /mixer dir.
That way all other parts of the skin use the (potentially updated) templates of the official version with your mixer mods.

I need to update the wiki accordingly.

**Comment by ronso0** [comment]
That said, your fix is welcome anyway as we/I indeed missed to change the LateNight waveform file paths in #12463 

Let me know if you want to issue the PR yourself (maybe just in order to get used to the process ; )
If not, I'll push this fix to 2.5 directly.

**Comment by ronso0** [comment]
I just noticed that there are more paths in LateNight that need to be fixed

controls/button_4state_display.xml:26:      <Unpressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:27:      <Pressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:33:      <Unpressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:34:      <Pressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:40:      <Unpressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:41:      <Pressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:47:      <Unpressed scalemode="STRETCH">skin:/<Variable ...
controls/button_4state_display.xml:48:      <Pressed scalemode="STRETCH">skin:/<Variable ...
style_classic.qss:2234:  image: url(skin:../LateNight/classic/buttons/..
style_classic.qss:2237:  image: url(skin:../LateNight/classic/buttons/..
style_palemoon.qss:2716:  image: url(skin:../LateNight/palemoon/buttons/..
style.qss:201:    image: url(skin:../LateNight/palemoon/buttons/btn__search.svg);
style.qss:211:    image: url(skin:../LateNight/palemoon/buttons/btn__search_disabled.svg);
toolbar.xml:273:      <Template src="skin:/controls/button_4state_display.xml">
waveforms_container.xml:23:                  <Template src="skin:waveform.xml">
waveforms_container.xml:40:                  <Template src="skin:waveform.xml">
waveforms_container.xml:53:                  <Template src="skin:waveform.xml">
waveforms_container.xml:66:                  <Template src="skin:waveform.xml">

Do you want to take care of that, too?

**Comment by morgannunan** [comment]
Yeah, I'll fix them, no problem.

**Comment by JoergAtGithub** [comment]
I can confirm this with LateNigh64 on Windows

**Comment by morgannunan** [comment]
Alright, I cloned this repo, made the new branch, made those fixes and committed them. I'm trying to push up my new branch but it says permission denied. How do I get permission to make a branch here?

**Comment by ronso0** [comment]
Please take a look at https://github.com/mixxxdj/mixxx/blob/main/CONTRIBUTING.md
You push your fixes (branch which is **not** named like the Mixxx default brnach `main`) to your repo and open a PR. A link for this is provided by git CLI when you've pushed and in the Github web UI at https://github.com/morgannunan/mixxx/branches.

**Comment by morgannunan** [comment]
OK, PR is in. This is apparently a problem for the other themes as well, as those also have relative paths. I haven't tested them, though.

**Comment by daschuer** [comment]
Fixed via https://github.com/mixxxdj/mixxx/pull/13501
