### ISSUE TITLE
Mixxx froze during normal operation

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#13454]
### Bug Description

I was playing a track on my Roland DJ-505 and, enabled the automatic looping in advance and let the track play.
Then I was looking up something on my phone and when I got back to the PC, the loading spinner mouse pointer from MacOS was shown when I looked at mixxx
I could not click anything in the UI, however, the faders and EQs on the DJ controller were sill responding.

I had to force quit the mixxx application.

### Version

2.4.1

### OS

macOS 14.5 (M1)

**Comment by Swiftb0y** [comment]
Thank you for reporting your issue. Please understand that in order for us to be able to properly debug this, we need a backtrace from the point of them when mixxx is stick. Have a look at the wiki for finding out how to create one: https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

**Comment by spotlesscoder** [comment]
Now my Mac even completely crashed.
Not 100% sure but I think it was the same track that I was playing last time when it froze. 
The track was Will Rees & Asteroid - Exhilarate

Would the apple crash report logs help you?
I will not eagerly provide them because I have to check whether they contain sensitive data

**Comment by Swiftb0y** [comment]
I don't remember. I think the crash reports do contain a backtrace, but you need a MacOS computer to view them or some garbage like that. If you're able to collect a backtrace using the guide I linked to previously, that would be easiest for us to work with and best for you because it should contain no sensitive data (except maybe filesystem paths containing your username).

**Comment by spotlesscoder** [comment]
I'm gonna close this as I'm not sure whether I'll find the time to try and reproduce this in the near future
