### ISSUE TITLE
Enabling headphones in a channel auto moves fader to 0

### ISSUE THREAD

**Issue by xxxmicrobexxx** [mixxxdj/mixxx#13718]
### Feature Description

I am pretty new to Mixx, but having tried other software, I am really liking it.   I am also pretty new to using a mixer so this may be a dumb thing to request, happy to hear why.

Sometimes when previewing a track in headphones I forget to move the fader to 0 so the sound comes out the speakers.  It seems like a nice feature would be that a long press on the headphone icon activates the headphones and also drops the fader right down on that channel.

![image](https://github.com/user-attachments/assets/9ec1db20-395c-4a01-b1f3-434b65bde62b)

I am not quite sure how this would work in a controller, can the same behaviour happen?

Thanks for all the work that has been done on Mixx, I wish I knew enough C++ to be able to do this and contribute to the codebase.

**Comment by ronso0** [comment]
Yes, this could be implemented in the c++ codebase¹ or in the mapping script.
_¹so it is applied when long-pressing the Pfl button in both GUI or on the controller_

But.. isn't it easier to get used to pulling down the Vol fader instead of having to remember to **long**-press the Pfl button?

___
@Swiftb0y I think this only about the mixer behaviour, and happens with both main mix routed to an output or indivial deck outputs (with external mixer).

**Comment by daschuer** [comment]
All actions that are affecting other controls are probably not very intuitiv. I can imagine to an alternativ PLF button that switches between main mix and PLF, just like on non DJ audio gear. But with this is it also easy to mess up the mix.

**Comment by xxxmicrobexxx** [comment]
> It sounds like you don't have your audio routed right and now you want to work around that. Can you post a screenshot of your audio output settings?

![mixx1](https://github.com/user-attachments/assets/359534ec-ef7e-4171-a5db-542d92ddbb38)

**Comment by xxxmicrobexxx** [comment]
> But.. isn't it easier to get used to pulling down the Vol fader instead of having to remember to **long**-press the Pfl button?

You could say that about anything that has a long click.  Does it matter if there is more than one way to do something and some people use one method and some people use the other?

To me, a single action - long click on Pfl - seems more intuitive that clicking Pfl and moving fader, two actions to achieve a single outcome.

**Comment by daschuer** [comment]
Do you know such feature from other applications? 

Since you proposal will also put the controller slider in out of sync state and some user use the crossfader an not the volume slider, I am reluctant to put it into the main branch. You can however implement it in your fork or controller mapping.

**Comment by Swiftb0y** [comment]
> Sometimes when previewing a track in headphones I forget to move the fader to 0 so the sound comes out the speakers. It seems like a nice feature would be that a long press on the headphone icon activates the headphones and also drops the fader right down on that channel.

So you want to preview the channel on your headphone but mute it on the speakers? I assume thats just because you forgot to pull down the mixer channel, right?

While I'm not opposed to the idea of adding a long-press action to the PFL button, I do want to raise the point that this may confuse people that are used to Numark Hardware. On Numark Controllers, the PFL button doesn't act as a channel toggle like in mixxx. It rather solos the channel for PFL (so you only need a single button press when you eg want to preview channel 1 instead of 2) and when you want to pfl multiple channels at the same time, you'll need to press and release multiple buttons at once (which somewhat implies a long-press).

**Comment by xxxmicrobexxx** [comment]
> While I'm not opposed to the idea of adding a long-press action to the PFL button, I do want to raise the point that this may confuse people that are used to Numark Hardware. On Numark Controllers, the PFL button doesn't act as a channel toggle like in mixxx. It rather solos the channel for PFL (so you only need a single button press when you eg want to preview channel 1 instead of 2) and when you want to pfl multiple channels at the same time, you'll need to press and release multiple buttons at once (which somewhat implies a long-press).

I fully understand how hard it is to be all things to all hardware.  Perhaps it could be an option to enable/disable?  Then we have the best of both worlds. ;o)

**Comment by davidlmorris** [comment]
I ran into this issue when creating my Radio Laneway Mixxx Midi controller (which I may eventually get around to making into a YouTube video and publishing the circuit boards and code since it works well), and I resolved it by moving the cross-fader (automagically with the button press) to the other deck.  I did this because I needed to keep the fader position for the decks synced up with the Midi Controler, and did not need the crossfader at all, since I was emulating a radio studio console.  @xxxmicrobexxx You might be able to invent some JS magic to do the same thing for your controller.

In my case, I could not understand the utility of having a 'headphone' button that did not automatically cut out the main/broadcast on that channel.  But I assume this is for some live club mixing purpose that I have never heard of.  The 'cue' button/switch in a radio studio works a bit like a Solo'ed 'Post Fade Listen' in a recording studio without it going out over the air.  (Usually with an option for 'split can' cueing, that is, headphones with left being broadcast and right being cue... but then AM radio was Mono back in my day!  Very useful during sports - keeping the footy ads going while coordinating with the race caller down the cue channel).

From a UX perspective having to do two discrete things for one outcome (cueing) is hardly ideal, but then breaking existing expectations isn't either. So @xxxmicrobexxx, I think your option idea is a good compromise.

**Comment by davidlmorris** [comment]
Oops.  I misspoke.  I didn't use the Crossfader (perhaps I did in an early version).  There is a command to [mute the channel](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls#control-[ChannelN]-mute), which I used for the same effect.  (And better since I could be playing a sample and have more than 1 deck in cue if I wanted to for some strange reason).
