### ISSUE TITLE
Pioneer FLX4 mapping dupicate use of shift+ channel cue

### ISSUE THREAD

**Issue by Aquassaut** [mixxxdj/mixxx#13813]
### Bug Description

Hi,
First off, thank you for this amazing piece of software and all the good work.

Pressing shift + channel cue on the flx4 triggers both [channel beat tap](https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Pioneer-DDJ-FLX4.midi.xml#L903) and [channel quantize toggle](https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Pioneer-DDJ-FLX4.midi.xml#L697), which is not super great as it makes it easy to mess up the bpm of a song.
I can't verify this as I don't have the device handy but seeing the config file the same issue seems to be present in the very similar DDJ-400.

I think quantize toggle is more useful but beat tap is the intended use of shift + channel cue [according to the manual](https://docs.pioneerdj.com/manuals/DDJ_FLX4_DRI1804A_manual/?page=26).

This issue doesn't block me (I simply use an edited mapping for myself) but it might be confusing for new users.

**Comment by ronso0** [comment]
Thanks for your report!

Do you have interest to provide a PR with a fix?

**Comment by Aquassaut** [comment]
Sure can, however I'd like some guidance, maybe by the original mapping authors, as to which effect to keep.

**Comment by Aquassaut** [comment]
It seems that @jusko added the quantize toggle behavior under the impression that the mapping wasn't used [in this commit](https://github.com/mixxxdj/mixxx/commit/3120764eb5e3b4151601e79408d1a3524ab5306b) so he might have some useful insight into it

**Comment by jusko** [comment]
Hi @Aquassaut, good spot on this. It's been a _long_ time since that commit... but can say for sure that beat tap was never something I used so it was probably an oversight. Weird that the bug never got picked up until now. I guess quantize toggle is rarely used and even less often "tapped".

I would think to just remove beat tap as it's not really a useful feature. The mixxx hardware manual documents for quantize toggle, which as you say is more useful.

**Comment by ronso0** [comment]
Note that in Mixxx 2.5 we added `tempo_tap` which allows manual syncing BPM to external sources.
