### ISSUE TITLE
Contributor agreement includes permission to re-license contributions under arbitrary terms, including non-free terms

### ISSUE THREAD

**Issue by rah2501** [mixxxdj/mixxx#14075]
### Bug Description

The [agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) states that

> if we cannot reach you within 30 days by the email address you provide below then **you permit Mixxx to re-license your contributions without your explicit permission**

which places no restriction at all on the kinds of license that contributions can be re-licensed under.  That means contributions could be re-licensed under non-free terms.  This prevents me from contributing to Mixxx.

Could the agreement be changed to restrict re-licensing to only free software, copyleft licenses?

 For why this is an issue, see for example:

 https://xonotic.org/faq/#what-prompted-the-split-from-nexuiz

https://hexchat.github.io/shareware.html

Also Ardour re-licensed as Mixbus but I can't find a link to confirm that yet.

**Comment by daschuer** [comment]
The current Mixxx license is already not a plain GPL license. We have an app store exception here: 
https://github.com/mixxxdj/mixxx/blob/f0ce199b4383595ec46c92f974996cdefd198d52/LICENSE#L316

Since we cannot predict what will happen with Mixxx, which may require additional GPL exceptions, so we won't change the agreement. 

Mixxx has contributions of 330+ people right now. Each on of them has signed the agreement and is able to block us from changing the license including their contributions to something else than GPL 2.0 or later. This brings a high level of trust that we don't make Mixxx closed source or something you might be afraid of. 

I am sorry if you still hesitate to contribute under this conditions.

**Comment by rah2501** [comment]
> I am sorry if you still hesitate to contribute under this conditions.

I do.  I am likewise sorry :-(
